import Footer from '@/components/Footer/Footer';
import NavBar from '@/components/NavBar/NavBar';
import { Chakra } from '@/context/CustomChakraProvider';
import { SessionProvider } from 'next-auth/react';
import { AppProps } from 'next/app';
import Head from 'next/head';
import { Suspense } from 'react';
import { SWRConfig } from 'swr';

export default function App({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  return (
    <SessionProvider session={session}>
      <SWRConfig>
        <Chakra cookies={pageProps.cookies}>
          {/* TODO:  replace null with 404 page*/}
          <Suspense fallback={null}>
            <Head>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/light-logo.svg" media="(prefers-color-scheme: dark)" />
              <link rel="icon" href="/dark-logo.svg" media="(prefers-color-scheme: light)" />
            </Head>
            <main
              style={{
                maxWidth: '1200px',
                margin: 'auto',
                // To push footer to bottom of page
                minHeight: '100vh',
                display: 'flex',
                flexDirection: 'column',
              }}
            >
              <NavBar />
              <Component {...pageProps} style={{ flex: 1 }} />
              <Footer />
            </main>
          </Suspense>
        </Chakra>
      </SWRConfig>
    </SessionProvider>
  );
}
